const PlayersList = {
  0: {
    id: 89304,
    first_name: "Novak",
    last_name: "Djokovic",
    full_name: "Novak Djokovic",
    country: "Serbia",
  },
  1: {
    id: 86928,
    first_name: "Rafael",
    last_name: "Nadal",
    full_name: "Rafael Nadal",
    country: "Spain",
  },
  2: {
    id: 342990,
    first_name: "Alexander",
    last_name: "Zverev",
    full_name: "Alexander Zverev",
    country: "Germany",
  },
  3: {
    id: 91668,
    first_name: "Potro",
    last_name: "Del",
    full_name: "Potro Del",
    country: "Argentina",
  },
  4: {
    id: 93378,
    first_name: "Kevin",
    last_name: "Anderson",
    full_name: "Kevin Anderson",
    country: "South Africa",
  },
  5: {
    id: 86064,
    first_name: "Roger",
    last_name: "Federer",
    full_name: "Roger Federer",
    country: "Switzerland",
  },
  6: {
    id: 94410,
    first_name: "Kei",
    last_name: "Nishikori",
    full_name: "Kei Nishikori",
    country: "Japan",
  },
  7: {
    id: 262500,
    first_name: "Dominic",
    last_name: "Thiem",
    full_name: "Dominic Thiem",
    country: "Austria",
  },
  8: {
    id: 96732,
    first_name: "John",
    last_name: "Isner",
    full_name: "John Isner",
    country: "USA",
  },
  9: {
    id: 92334,
    first_name: "Marin",
    last_name: "Cilic",
    full_name: "Marin Cilic",
    country: "Croatia",
  },
  10: {
    id: 540492,
    first_name: "Karen",
    last_name: "Khachanov",
    full_name: "Karen Khachanov",
    country: "Russia",
  },
  11: {
    id: 734208,
    first_name: "Stefanos",
    last_name: "Tsitsipas",
    full_name: "Stefanos Tsitsipas",
    country: "Greece",
  },
  12: {
    id: 387492,
    first_name: "Borna",
    last_name: "Coric",
    full_name: "Borna Coric",
    country: "Croatia",
  },
  13: {
    id: 108678,
    first_name: "Milos",
    last_name: "Raonic",
    full_name: "Milos Raonic",
    country: "Canada",
  },
  14: {
    id: 92616,
    first_name: "Fabio",
    last_name: "Fognini",
    full_name: "Fabio Fognini",
    country: "Italy",
  },
  15: {
    id: 981036,
    first_name: "Daniil",
    last_name: "Medvedev",
    full_name: "Daniil Medvedev",
    country: "Russia",
  },
  16: {
    id: 346230,
    first_name: "Lucas",
    last_name: "Pouille",
    full_name: "Lucas Pouille",
    country: "France",
  },
  17: {
    id: 100332,
    first_name: "Agut",
    last_name: "Bautista",
    full_name: "Agut Bautista",
    country: "Spain",
  },
  18: {
    id: 267306,
    first_name: "Marco",
    last_name: "Cecchinato",
    full_name: "Marco Cecchinato",
    country: "Italy",
  },
  19: {
    id: 291606,
    first_name: "Diego",
    last_name: "Schwartzman",
    full_name: "Diego Schwartzman",
    country: "Argentina",
  },
  20: {
    id: 155040,
    first_name: "David",
    last_name: "Goffin",
    full_name: "David Goffin",
    country: "Belgium",
  },
  21: {
    id: 157236,
    first_name: "Nikoloz",
    last_name: "Basilashvili",
    full_name: "Nikoloz Basilashvili",
    country: "Georgia",
  },
  22: {
    id: 244812,
    first_name: "Busta",
    last_name: "Carreno",
    full_name: "Busta Carreno",
    country: "Spain",
  },
  23: {
    id: 141498,
    first_name: "Grigor",
    last_name: "Dimitrov",
    full_name: "Grigor Dimitrov",
    country: "Bulgaria",
  },
  24: {
    id: 707508,
    first_name: "Denis",
    last_name: "Shapovalov",
    full_name: "Denis Shapovalov",
    country: "Canada",
  },
  25: {
    id: 86940,
    first_name: "Fernando",
    last_name: "Verdasco",
    full_name: "Fernando Verdasco",
    country: "Spain",
  },
  26: {
    id: 86496,
    first_name: "Richard",
    last_name: "Gasquet",
    full_name: "Richard Gasquet",
    country: "France",
  },
  27: {
    id: 1207446,
    first_name: "Minaur",
    last_name: "De",
    full_name: "Minaur De",
    country: "Australia",
  },
  28: {
    id: 392304,
    first_name: "Kyle",
    last_name: "Edmund",
    full_name: "Kyle Edmund",
    country: "United Kingdom",
  },
  29: {
    id: 606618,
    first_name: "Frances",
    last_name: "Tiafoe",
    full_name: "Frances Tiafoe",
    country: "USA",
  },
  30: {
    id: 88428,
    first_name: "Gilles",
    last_name: "Simon",
    full_name: "Gilles Simon",
    country: "France",
  },
  31: {
    id: 87756,
    first_name: "Philipp",
    last_name: "Kohlschreiber",
    full_name: "Philipp Kohlschreiber",
    country: "Germany",
  },
  32: {
    id: 89076,
    first_name: "Gael",
    last_name: "Monfils",
    full_name: "Gael Monfils",
    country: "France",
  },
  33: {
    id: 230970,
    first_name: "Steve",
    last_name: "Johnson",
    full_name: "Steve Johnson",
    country: "USA",
  },
  34: {
    id: 94986,
    first_name: "Jeremy",
    last_name: "Chardy",
    full_name: "Jeremy Chardy",
    country: "France",
  },
  35: {
    id: 198702,
    first_name: "John",
    last_name: "Millman",
    full_name: "John Millman",
    country: "Australia",
  },
  36: {
    id: 88650,
    first_name: "Andreas",
    last_name: "Seppi",
    full_name: "Andreas Seppi",
    country: "Italy",
  },
  37: {
    id: 95910,
    first_name: "Martin",
    last_name: "Klizan",
    full_name: "Martin Klizan",
    country: "Slovakia",
  },
  38: {
    id: 226722,
    first_name: "Joao",
    last_name: "Sousa",
    full_name: "Joao Sousa",
    country: "Portugal",
  },
  39: {
    id: 816264,
    first_name: "Taylor",
    last_name: "Fritz",
    full_name: "Taylor Fritz",
    country: "USA",
  },
  40: {
    id: 537804,
    first_name: "Nicolas",
    last_name: "Jarry",
    full_name: "Nicolas Jarry",
    country: "Chile",
  },
  41: {
    id: 235416,
    first_name: "Dusan",
    last_name: "Lajovic",
    full_name: "Dusan Lajovic",
    country: "Serbia",
  },
  42: {
    id: 95130,
    first_name: "Malek",
    last_name: "Jaziri",
    full_name: "Malek Jaziri",
    country: "Tunisia",
  },
  43: {
    id: 267330,
    first_name: "Pierre",
    last_name: "Herbert",
    full_name: "Pierre Herbert",
    country: "France",
  },
  44: {
    id: 98466,
    first_name: "Matthew",
    last_name: "Ebden",
    full_name: "Matthew Ebden",
    country: "Australia",
  },
  45: {
    id: 95376,
    first_name: "Adrian",
    last_name: "Mannarino",
    full_name: "Adrian Mannarino",
    country: "France",
  },
  46: {
    id: 286632,
    first_name: "Marton",
    last_name: "Fucsovics",
    full_name: "Marton Fucsovics",
    country: "Hungary",
  },
  47: {
    id: 91818,
    first_name: "Sam",
    last_name: "Querrey",
    full_name: "Sam Querrey",
    country: "USA",
  },
  48: {
    id: 93402,
    first_name: "Leonardo",
    last_name: "Mayer",
    full_name: "Leonardo Mayer",
    country: "Argentina",
  },
  49: {
    id: 499278,
    first_name: "Hyeon",
    last_name: "Chung",
    full_name: "Hyeon Chung",
    country: "South Korea",
  },
  50: {
    id: 278358,
    first_name: "Jan",
    last_name: "Struff",
    full_name: "Jan Struff",
    country: "Germany",
  },
  51: {
    id: 295044,
    first_name: "Damir",
    last_name: "Dzumhur",
    full_name: "Damir Dzumhur",
    country: "Bosnia & Herzegovina",
  },
  52: {
    id: 676710,
    first_name: "Matteo",
    last_name: "Berrettini",
    full_name: "Matteo Berrettini",
    country: "Italy",
  },
  53: {
    id: 96264,
    first_name: "Robin",
    last_name: "Haase",
    full_name: "Robin Haase",
    country: "Netherlands",
  },
  54: {
    id: 100110,
    first_name: "Mikhail",
    last_name: "Kukushkin",
    full_name: "Mikhail Kukushkin",
    country: "Kazakhstan",
  },
  55: {
    id: 97974,
    first_name: "Marius",
    last_name: "Copil",
    full_name: "Marius Copil",
    country: "Romania",
  },
  56: {
    id: 87300,
    first_name: "Stan",
    last_name: "Wawrinka",
    full_name: "Stan Wawrinka",
    country: "Switzerland",
  },
  57: {
    id: 133320,
    first_name: "Benoit",
    last_name: "Paire",
    full_name: "Benoit Paire",
    country: "France",
  },
  58: {
    id: 219582,
    first_name: "Denis",
    last_name: "Kudla",
    full_name: "Denis Kudla",
    country: "USA",
  },
  59: {
    id: 146520,
    first_name: "Guido",
    last_name: "Pella",
    full_name: "Guido Pella",
    country: "Argentina",
  },
  60: {
    id: 526152,
    first_name: "Jordan",
    last_name: "Thompson",
    full_name: "Jordan Thompson",
    country: "Australia",
  },
  61: {
    id: 97176,
    first_name: "Peter",
    last_name: "Gojowczyk",
    full_name: "Peter Gojowczyk",
    country: "Germany",
  },
  62: {
    id: 86802,
    first_name: "Feliciano",
    last_name: "Lopez",
    full_name: "Feliciano Lopez",
    country: "Spain",
  },
  63: {
    id: 575622,
    first_name: "Cameron",
    last_name: "Norrie",
    full_name: "Cameron Norrie",
    country: "United Kingdom",
  },
  64: {
    id: 228144,
    first_name: "Aljaz",
    last_name: "Bedene",
    full_name: "Aljaz Bedene",
    country: "Slovenia",
  },
  65: {
    id: 355698,
    first_name: "Yoshihito",
    last_name: "Nishioka",
    full_name: "Yoshihito Nishioka",
    country: "Japan",
  },
  66: {
    id: 374952,
    first_name: "Nick",
    last_name: "Kyrgios",
    full_name: "Nick Kyrgios",
    country: "Australia",
  },
  67: {
    id: 96078,
    first_name: "Mischa",
    last_name: "Zverev",
    full_name: "Mischa Zverev",
    country: "Germany",
  },
  68: {
    id: 291804,
    first_name: "Taro",
    last_name: "Daniel",
    full_name: "Taro Daniel",
    country: "Japan",
  },
  69: {
    id: 283782,
    first_name: "Guido",
    last_name: "Andreozzi",
    full_name: "Guido Andreozzi",
    country: "Argentina",
  },
  70: {
    id: 100944,
    first_name: "Vinolas",
    last_name: "Ramos",
    full_name: "Vinolas Ramos",
    country: "Spain",
  },
  71: {
    id: 137832,
    first_name: "Filip",
    last_name: "Krajinovic",
    full_name: "Filip Krajinovic",
    country: "Serbia",
  },
  72: {
    id: 953388,
    first_name: "Hubert",
    last_name: "Hurkacz",
    full_name: "Hubert Hurkacz",
    country: "Poland",
  },
  73: {
    id: 306858,
    first_name: "Baena",
    last_name: "Carballes",
    full_name: "Baena Carballes",
    country: "Spain",
  },
  74: {
    id: 220080,
    first_name: "Tennys",
    last_name: "Sandgren",
    full_name: "Tennys Sandgren",
    country: "USA",
  },
  75: {
    id: 429972,
    first_name: "Maximilian",
    last_name: "Marterer",
    full_name: "Maximilian Marterer",
    country: "Germany",
  },
  76: {
    id: 211014,
    first_name: "Federico",
    last_name: "Delbonis",
    full_name: "Federico Delbonis",
    country: "Argentina",
  },
  77: {
    id: 87174,
    first_name: "Ivo",
    last_name: "Karlovic",
    full_name: "Ivo Karlovic",
    country: "Croatia",
  },
  78: {
    id: 87072,
    first_name: "Tomáš",
    last_name: "Berdych",
    full_name: "Tomáš Berdych",
    country: "Czech Republic",
  },
  79: {
    id: 758148,
    first_name: "Jaume",
    last_name: "Munar",
    full_name: "Jaume Munar",
    country: "Spain",
  },
  80: {
    id: 535932,
    first_name: "Ilya",
    last_name: "Ivashka",
    full_name: "Ilya Ivashka",
    country: "Belarus",
  },
  81: {
    id: 380640,
    first_name: "Mackenzie",
    last_name: "Mcdonald",
    full_name: "Mackenzie Mcdonald",
    country: "USA",
  },
  82: {
    id: 92604,
    first_name: "Pablo",
    last_name: "Andujar",
    full_name: "Pablo Andujar",
    country: "Spain",
  },
  83: {
    id: 94362,
    first_name: "Ernests",
    last_name: "Gulbis",
    full_name: "Ernests Gulbis",
    country: "Latvia",
  },
  84: {
    id: 99102,
    first_name: "Thomas",
    last_name: "Fabbiano",
    full_name: "Thomas Fabbiano",
    country: "Italy",
  },
  85: {
    id: 102492,
    first_name: "Bernard",
    last_name: "Tomic",
    full_name: "Bernard Tomic",
    country: "Australia",
  },
  86: {
    id: 230460,
    first_name: "Bradley",
    last_name: "Klahn",
    full_name: "Bradley Klahn",
    country: "USA",
  },
  87: {
    id: 583398,
    first_name: "Laslo",
    last_name: "Djere",
    full_name: "Laslo Djere",
    country: "Serbia",
  },
  88: {
    id: 342138,
    first_name: "Jozef",
    last_name: "Kovalik",
    full_name: "Jozef Kovalik",
    country: "Slovakia",
  },
  89: {
    id: 267294,
    first_name: "Radu",
    last_name: "Albot",
    full_name: "Radu Albot",
    country: "Moldova",
  },
  90: {
    id: 1112340,
    first_name: "Ugo",
    last_name: "Humbert",
    full_name: "Ugo Humbert",
    country: "France",
  },
  91: {
    id: 94746,
    first_name: "Pablo",
    last_name: "Cuevas",
    full_name: "Pablo Cuevas",
    country: "Uruguay",
  },
  92: {
    id: 137412,
    first_name: "Ryan",
    last_name: "Harrison",
    full_name: "Ryan Harrison",
    country: "USA",
  },
  93: {
    id: 100686,
    first_name: "Vasek",
    last_name: "Pospisil",
    full_name: "Vasek Pospisil",
    country: "Canada",
  },
  94: {
    id: 387432,
    first_name: "Cristian",
    last_name: "Garin",
    full_name: "Cristian Garin",
    country: "Chile",
  },
  95: {
    id: 102114,
    first_name: "Evgeny",
    last_name: "Donskoy",
    full_name: "Evgeny Donskoy",
    country: "Russia",
  },
  96: {
    id: 251154,
    first_name: "Jiri",
    last_name: "Vesely",
    full_name: "Jiri Vesely",
    country: "Czech Republic",
  },
  97: {
    id: 782412,
    first_name: "Reilly",
    last_name: "Opelka",
    full_name: "Reilly Opelka",
    country: "USA",
  },
  98: {
    id: 108408,
    first_name: "Mirza",
    last_name: "Basic",
    full_name: "Mirza Basic",
    country: "Bosnia & Herzegovina",
  },
  99: {
    id: 640542,
    first_name: "Andrey",
    last_name: "Rublev",
    full_name: "Andrey Rublev",
    country: "Russia",
  },
};

export { PlayersList };
